name: Release build

on:
    push:
        tags:
            - 'v*'

jobs:
    zipper:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: zip output
              run: zip autoskip_ads_${{github.ref.tags.name}}.zip *
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                files: autoskip_ads_${{github.ref.tags.name}}.zip
            - name: test
              run: ls