name: Release build

on:
    push:
        tags:
            - 'v*'

jobs:
    zipper:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: zip output
              run: zip autoskip_ads_${{github.ref_name}}.zip *
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                name: "Release ${{github.ref_name}}""
                tag_name: ${{github.ref_name}}
                files: autoskip_ads_${{github.ref_name}}.zip
            - name: test
              run: ls